### ISSUE TITLE
BUG: Add Reaticulate FX button does not seem to work

### ISSUE THREAD

**Issue by creynders** [jtackaberry/reaticulate#24] opened 2018-01-11 20:25 UTC
When I select a track and then click the "Add Reaticulate FX" button nothing seems to happen. The button does respond to the click, but it still just shows "Reaticulate is not enabled for this track".
I enabled reaticulate debugging but it doesn't show anything else but "Reaticulate debugging is enabled"
If I deselect the track it shows correctly "No track selected".

This is with Reaper v5.70/64 on Mac OS X 10.12.6

**Comment by jtackaberry** [comment] 2018-01-11 20:34
Duplicate of #15 .  Workaround is to manually open the Open FX window once, and thereafter the Add Reaticulate FX button will work.

I really need to get a new release out that at least addresses these closed issues. :/

**Closed by jtackaberry** 2018-01-11 20:34 UTC

**Comment by creynders** [comment] 2018-01-11 20:51
Ah yes, that did the trick! Thanks both for the support and what seems to be a great reaper plugin!
