### ISSUE TITLE
Reaticulate not opening in REAPack

### ISSUE THREAD

**Issue by mx5run** [jtackaberry/reaticulate#160] opened 2022-01-30 01:42 UTC
Hi
This may be just me or there is an issue I am not aware of.
I am running Win7 Pro 64bit and Reaper 6.46.
The message I am getting is this:
        "Download failed: SSL  connect error (35):schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326)-This error usually occurs when a fatel SSL/TLS alert is received (e.g. handshake failed). More details may be available in the Windows System event log.
https://reaticulate.com prerelease.xml"
I have REAPack installed and running fine. 
Is there something I am missing or is this a quirk of Win7?

Thank You

**Comment by jtackaberry** [comment] 2022-01-30 01:58
Is this something that used to work and recently broke, or were you adding the Reaticulate ReaPack for the first time?

**Comment by jtackaberry** [comment] 2022-01-30 03:01
@mx5run ok, I installed Windows 7 in a VM (finding an ISO took some doing :)) and was able to reproduce the problem.

The root cause is that I recently moved reaticulate.com to a new server, and said new server has much stronger and more modern security settings.  I have to weak things somewhat in order to support Windows 7.  I believe I've found an option that's palatable.

The other thing you'll need to do -- assuming you haven't done it already -- is install a new root certificate in the system's trust store.  This is already trusted by every other supported OS, but as Win7 has been EoLed for 2 years, it doesn't have it.

Download https://letsencrypt.org/certs/isrgrootx1.der

Then double click the file in Explorer and follow these steps:
- Click "Install Certificate..."
- Next
- Select "Place all certificates in the following store" radio button
- Click Browse
- Select "Trusted Root Certification Authorities" and click OK
- Click Next and Finish
- Acknowledge any further prompts informing you about the installation

Let me know how that goes.

**Comment by mx5run** [comment] 2022-01-30 22:44
Hi, Thank you for answering back. This was adding Reaticulate for the first
time. I saw before I responded to this email your followup. I will continue
there with your suggestion.
And make any other comments from that email.
Again Thank You.

**Comment by mx5run** [comment] 2022-01-30 22:48
OK. This will be a new adventure for me , but worth the try and for
learning purposes.  I know that my days are short with Win7, but I dislike
Win10.
Again Thank You. I shall try to get back to you if this works or not.
Glenn

**Comment by mx5run** [comment] 2022-01-31 00:02
Hi Jason,
THANK YOU for the suggestion. It worked flawlessly, which for a Windows
unit gets to be rare.
It does work. Now for the new learning curve.
Thanks Glenn

**Comment by jtackaberry** [comment] 2022-01-31 00:09
Great!

> It worked flawlessly, which for a Windows unit gets to be rare.

True in the best of times, but especially when it's out of support :)

Will close this issue now.  Cheers Glenn.

**Closed by jtackaberry** 2022-01-31 00:09 UTC
