### ISSUE TITLE
Different Articulate Management 

### ISSUE THREAD

**Issue by Kylo81** [jtackaberry/reaticulate#136] opened 2021-07-01 01:02 UTC
Hello 

I wanted to ask is there other alternative developments   being worked on for reticulate? I feel as if though typing variables for the rebank file per library for this great plugin can be extremely time consuming for each and every library someone will purchase 

I came across BSRO articulate  however the developer left the community with empty hopes for reaper users, when he announced it was discontinued. I haven’t found a way around trying to manage different midi outs within one instance of kontakt in Reaper. However I did manage to find it was completed for FL studio (with him being an FL studios user) 

Adding on, you’d have to load BSRO over Kontakt and when trying to play other midi tracks for some reason BSRO only reads the 1st midi for an unknown reason. 

It would be great for work flow purposes. Reaticulate is a great plugin but will it ever be developed to the idea mentioned above?

**Comment by jtackaberry** [comment] 2021-07-01 01:37
Hi @Kylo81

Browsing through the [open issues in this project](https://github.com/jtackaberry/reaticulate/issues/) will give you a sense of what I have in mind for it.

Indeed, the current situation of needing to create banks using a text editor has always been a stopgap, and a proper GUI is high on my list of things from a UX perspective (it's issue #5).

There's some plumbing I need to finish in the next release, and then the GUI for creating/editing banks (articulation maps) will be in the next major release after that.

The problem isn't ideas or aspirations, only free time, which unfortunately is a scarce commodity.  I am actively working on it, but it's moving rather slowly.  Those major features notwithstanding, my commitment is to actively fix bugs.  I will not let user impacting bugs (i.e. those users can't easily work around) languish in the product if I am aware of them.

**Comment by Kylo81** [comment] 2021-07-01 02:09
I understand it’s a process with coding and programming and if you don’t have a team it will take longer but I appreciate your commitment to this and the timely response

I do look forward to seeing the updates

**Comment by jtackaberry** [comment] 2021-07-01 02:19
Thanks!  Feel free to subscribe to issue #5 (there is a Subscribe link on the issue page) to learn about updates and when this is implemented.

I'll close this issue here, but you're welcome to ask followup questions if you like.

**Closed by jtackaberry** 2021-07-01 02:19 UTC
Labels: question
