### ISSUE TITLE
Wrong bank displayed for selected track

### ISSUE THREAD

**Issue by rgruet** [jtackaberry/reaticulate#90] opened 2020-04-29 14:21 UTC
### Problem

After I add Reaticulate with different banks to several tracks and save the project, when I reopen it and select a track the bank displayed is often incorrect.

Frequently the _same_ bank is displayed for several tracks (i.e. when I switch the track selected the bank displayed stays the same).

When I close **without saving** the project and reopen it, I may get different results each time, e.g. a different bank (relatively to the previous iteration) displayed for several tracks, or even the _correct_ configuration is shown (correct bank displayed for each track)!

Repeating the same sequence, but this time **saving** the project before closing and reopening it doesn't seem to make much difference.

There is no discernable pattern, no obvious causal relationship between my actions and what I get, or at least that I could notice. It looks like this is **random** (but frequent!).

### Steps to the problem

I created a simple Reaper project with two empty tracks ([Test Bug Reaticulate Apr 2020.RPP.zip](https://github.com/jtackaberry/reaticulate/files/4552192/Test.Bug.Reaticulate.Apr.2020.RPP.zip))

- First track "Violin1", added Reaticulate to the track with (arbitrarily) bank Factory > Spitfire > Chamber Strings > V1 Core
- Second track "Viola", added Reaticulate to the track with bank Factory > Spitfire > Chamber Strings > Va Decorative.

At that point if I select a track I always get the corresponding bank correctly displayed by Reaticulate.

Then I *save* the project, close it and reopen it and... (not always but frequently) I will see the same bank displayed for the two tracks.
If I close the project without saving and reopen it, I may (or not) get the correct bank displayed this time.
Sorry, that's hard to describe because as I say earlier there is no clear pattern :-( Basically all what I do for getting the problem is close the project with or without saving it, and reopen it.
 
### My configuration

  - MacOS Mojave (10.14.6)
  - Reaper 6.09 (just updated, but problem already existed with 6.08)
  - Reaticulate 0.4.5 - I tried downgrading to 0.4.4, problem still present.
  - I used an empty Reaticulate.reabank to rule out the possibility of an error
    in my definitions. 
  - ReaScript 1.002 (I tried downgrading to 1.001, 1.000, 0.999, problem persists).
  - SWS 2.11.0 (beta) - I tried downgrading to 2.10.0.1 (stable), problem persists.

Richard

**Comment by jtackaberry** [comment] 2020-05-23 16:46
Oh boy, this one looks like at tricky one. :)

I've tried to reproduce from your test case but after trying a couple dozen times by closing/reopening.  In all cases the two tracks showed the proper bank in the GUI.

So this could be a platform difference: I'm on Windows, rather than Mac.  And there is a subtlety here that *could* be platform specific.

The next time this happens, for the two tracks that are showing the same bank:
1. Open the Reaticulate JSFX window
2. Select "On" for "Show Debugging"
3. Resize the FX window if necessary so you can see all the information there
4. Note toward the bottom the value for `gmem_index` 

I'm quite interested to know if the two tracks show the *same* `gmem_index` value here.  If so, this is the root cause, and methinks I'll have a Reaper bug to report. :)

P.S. Sorry about the delay!

**Comment by rgruet** [comment] 2020-05-23 21:00
Hi Jason,

I just reproduced the issue on my test project: Reaticulate displays the **same** patch for the two tracks, and as you correctly guessed, the value of `gm_index` is the **same** in both cases.

Here are the screenshots of the two tracks' FX windows:

![Screenshot 2020-05-23 at 22 50 10](https://user-images.githubusercontent.com/6683823/82740418-d2ea5480-9d48-11ea-9ea6-9adf1a55d619.png)
![Screenshot 2020-05-23 at 22 50 20](https://user-images.githubusercontent.com/6683823/82740419-d54cae80-9d48-11ea-874e-e77e74191d09.png)

Cheers
Richard

**Comment by jtackaberry** [comment] 2020-05-23 23:16
Yeah, this is a pretty serious bug.  And it's almost certainly a race condition, perhaps influenced by system or Reaper configuration.

I fired up an OS X virtual machine I use for testing Reaticulate (also Mojave) and after reloading the project about 20 times, still wasn't able to reproduce.

But now that I understand the nature of the bug, I can create more of a stress test to try to trigger it, and a helper script to programmatically detect it.  I'll work on that.

But meanwhile, I've a couple other questions to try to converge on root cause:
1. When you encounter the issue, if you offline and online the Reaticulate JSFX on the track showing the wrong bank to "reboot" Reaticulate, does the JSFX now get a unique `gmem_index` and show the correct bank? 
2. Does this issue also occur for you with a fresh portable install of Reaper?  (Reaper has a few options related to parallel processing that could conceivably be involved here.)

Thanks!

**Comment by rgruet** [comment] 2020-05-24 13:07
Here is the result of my tests:

1. Setting the Reaticulate FX offline and then online on the track displaying the wrong patch **does solve the problem**. The correct patch is displayed.

2. Using a portable fresh installation of Reaper 6.10, I quicky observed the same problem, with the same patch being displayed for the 2 tracks, and the **same** `gmem_index` value. But to make things even more obscure, I kept testing and also ran into a case where the same patch was displayed for the 2 tracks, but with **different**  `gmem_index` value:

![Screenshot 2020-05-24 at 14 44 06](https://user-images.githubusercontent.com/6683823/82754417-11295780-9dcd-11ea-94fa-ee2ac40f8d9e.png)
![Screenshot 2020-05-24 at 14 44 10](https://user-images.githubusercontent.com/6683823/82754420-12f31b00-9dcd-11ea-82bc-abc35947df55.png)

(here the patch displayed was the "Vla Decorative" in both cases).

The problem appears or not when I open the project. it will not disappear until I quit (with or without saving, it doesn't seem to have an impact). On each open the problem may or may not appear, it looks random. Could it be related to a serialization / deserialization of Reaticulate data problem?

HTH

**Comment by rgruet** [comment] 2020-05-24 13:40
A few additional remarks:

1.  On test 1, setting Reaticulate offline / online consistently fixes the problem for the duration of the session, but the problem may reappear (or not) as usual on the next opening.

2. Regarding the weird case where the patches displayed are the same for the two tracks **and** the value of gmem_index is **different**: when it happened, I was unable to fix the problem by setting Reaticulate offline / online (I tried on the the wrong track, then on the other one to no avail). I had to **remove** Reaticulate from the faulty track and add it again (select the library and the patch) to get rid of the problem.

**Comment by jtackaberry** [comment] 2020-05-24 15:41
`#1` makes sense and is consistent with my hypothesis of root cause.

`#2` on the other hand is a head-scratcher.  It's quite possible that the `gmem_index` collision leads to other oddities like this.  Given that, and also given that I've made some nontrivial changes to how the UI knows what banks are assigned to which track in my development branch for what will become 0.5.0, I'm going to focus on the `gmem_index` collision problem right now.

So I spent a couple hours last night trying to reproduce the problem.  I created a project with 1000 tracks, and wrote a helper script to scan through all the instances and report on any collisions.  I just wasn't able to reproduce the problem using the recipe you laid out: I could close and reopen the project until the cows came home, no `gmem_index` collisions occurred.

But a thought occurred to me: it had always appeared that Reaper ensured some sort of serialization of track loading when projects are opened, which means the race condition the Reaticulate JSFX code tries to solve doesn't occur, and this was consistent with my own observations.  (It definitely wasn't consistent with yours though.)

I had the idea to restart Reaper and *not* load the Reaticulate UI before opening the project.  By doing this, some data initialization needed by the JSFX isn't done, and so the JSFX will load but not allocate their `gmem_index` yet, instead sitting patiently and waiting for that necessary data to get initialized by the Lua UI script.

Then I loaded up the UI, and unlike the loading case which (for me anyway) appears to be a sequential track-by-track process, this time all the JSFX sprang to life and all tried to allocate the `gmem_index` with heavy parallelism.  Here I was able to reproduce the collisions: the [JSFX code to avoid the race condition](https://github.com/jtackaberry/reaticulate/blob/3fe8299/jsfx/Reaticulate.jsfx#L1494) wasn't working.

I [asked for some advice on the Reaper forum](https://forum.cockos.com/showthread.php?p=2293072) but as this requires some fairly internal knowledge of how Reaper is implemented, it will depend on the Reaper devs noticing my question.  The API documentation is vague, and it's possible (at this point I'd say probable) that I've been making incorrect assumptions about how it works.

So the good news is that I *can* reproduce this issue.  Not quite in the same way you can, but I believe the underlying causes are the same.  The bad news is that fixing it properly, if it's not something Reaper itself can support, will require a fairly nontrivial fix.

I'm just surprised this hasn't come up yet from other users.  This is a pretty big problem -- basically Reaticulate is fundamentally broken with this bug -- so I'm still suspicious if there's something about your particular system that's atypical.  (That's incidental, a bug is a bug, it's more of a technical curiosity.)

**Comment by rgruet** [comment] 2020-05-24 22:02
Well, hardware-wise I have a good old 15" Macbook Pro (Mid 2014), i7 2.2.Ghz,  16GB RAM, 250GB SSD, plus a couple of external 1TB SSDs for the sound libraries, a FocusRite Scarlett 18i audio interface...

On the software side, MacOS Mojave 10.14.6, Reaper 6.10, and a bunch of others, but I can't think of a particular one that could interfere with Reaper at such an intimate level. But it could just be a timing problem, maybe on a different configuration things will not occur in such a way that the race condition can occur.

I know very little about EEL, but it doesn't seem to have a mutex-like mechanism (beyond the atomic variable access functions) which would allow to implement a _critical section_ sequentializing access by the RFX instances to the gmem_allocate() function.

However I think a critical section could be (poorly) implemented using the `atomic_setifequal()` EEL function.
Let's say that `c` is a variable in the space shared by all RFX instances (such as the reaticulate gmem space) which can take to values `UNSET_VALUE` and `SET_VALUE`, and is initially set to `UNSET_VALUE` (pick the value so it's _naturally_ so!). Then the following pseudo code implements a critical section:

```
local oldValue

// Acquire the lock:
do
    oldValue = atomic_setifequal(c, UNSET_VALUE, SET_VALUE)
    if oldValue == SET_VALUE then
      // Couldn't acquire the lock: waste some time in an interruptible way. Unfortunately 
      // there is no sleep() function in EEL, so we will just loop - very CPU inefficient,
      // but hopefully for a short time only.
    end
while oldValue == SET_VALUE

// Critical section. Here we can assume that c == SET_VALUE and that all other concurrent
//  RFX instances are waiting to set c, and are therefore not messing with the protected code.
// ... Protected code here...

// Release the lock:
oldValue = atomic_setifequal(c, SET_VALUE, UNSET_VALUE)
assert oldValue == SET_VALUE // (excess of control freakness ;-)
```

Just an untested idea...

**Comment by jtackaberry** [comment] 2020-05-24 22:26
This is effectively what the current code does.  It doesn't implement a spinlock as such, but it uses `atomic_setifequal()` to ensure serialization.  Instead of a global mutex, it synchronizes on the slot in the gmem buffer that it's interested in modifying.

The problem is that `atomic_setifequal()` doesn't appear to work on gmem buffers, or indeed JSFX global variables, only on local variables across different contexts in the same JSFX instance (`@serialize`, `@slider`, `@block`, etc.).  In other words, the variable `c` you mention that's shared by all RFX instances doesn't actually exist.

I'm experimenting some pretty brutal workarounds at the moment.

The first place I went was to the literature on CAS-free spinlock implementations.  There's Peterson's algorithm, but it only works with two competing threads, whereas in Reaticulate's case there can be arbitrarily many JSFX isntances.

Next I thought the concession I'd make would be to move the `gmem_index` allocation to the Lua side, which is a global instance.  But this has a nasty side effect: the communication of the gmem_index assignment would be done through a slider parameter, which will pollute the undo history with crap.  (The Lua API to set slider parameters mutates the undo history.)

I'm currently playing with another option: have the Lua side elect one of the JSFX instances to act as a lock manager, to grant a lock to another JSFX instance so it can synchronize the critical section.  (The Lua side *could* perform this function, but the Lua cycle rate is only about 30Hz, while JSFX `@block` (or `@sample`) executes much quicker.)

I have that basically working, but it's pretty gross.  I'm going to experiment again with the first idea to have the Lua script to `gmem_index` allocations.  I have a couple ideas to improve latency of the assignment and not pollute undo history.

**Comment by rgruet** [comment] 2020-05-24 22:59
Oops, I stupidly forgot that in your post on the Reaper forum you were mentioning that `atomic_setifequal()` didn't seem to work on gmem memory!

Good luck with your current creative "brutal workarounds" approach  ;-) - What else can you do anyway when there is no clean possibility available and just a spartan API documentation? 

Let me know if you need my testing or any other information.

**Comment by jtackaberry** [comment] 2020-05-24 23:36
Yeah, sigh, brutal workarounds are kinda par for the course with Reaper.  (Like the lengths I need to go to in order to [prevent mangling of the last touched FX](https://github.com/jtackaberry/reaticulate/blob/3fe8299e964eb49f3c434f8e2c8926282cf26a27/app/rfx.lua#L982).)

I hope to have something at least ready to test tomorrow evening.  Would you be ok surgically transplanting a couple files (`Reaticulate.jsfx` and `rfx.lua`) from your installation when the time comes?

**Comment by jtackaberry** [comment] 2020-05-25 00:24
Well, on the assumption that you *are*, here are those files. :)

I wanted to spend a bit more time testing and cleaning up the code, but I'm running out of gas for tonight, and I figured it might be better to get some early feedback from you heading into tomorrow evenint.

`Reaticulate.jsfx` replaces the file under `Effects/Reaticulate/jsfx/` and `rfx.lua` replaces the file in `Scripts/Reaticulate/app/`.  I recommend you backup the original files. :)

[Reaticulate-gmem_index-race-fix-20200524.zip](https://github.com/jtackaberry/reaticulate/files/4674680/Reaticulate-gmem_index-race-fix-20200524.zip)

**Comment by rgruet** [comment] 2020-05-25 11:06
Hi Jason,

I tried your files on my test project composed of 2 tracks, and on my ~20 trials it apparently worked (each selected track showed the correct library after opening the project). However in one occasion when I was selecting and deselecting the tracks more or less randomly I got the two tracks showing the _same_ patch. Unfortunately I couldn't reproduce the case. 
 
Then I added a third track "Cello" and tested again. This time I immediately (I think after the first project save and reopen) **ran into the problem** again:

![Screenshot 2020-05-25 at 12 25 29](https://user-images.githubusercontent.com/6683823/82805440-52307300-9e84-11ea-9f9f-71f792e89650.png)

As you can see in the debug data (or not see since it's so tiny ;-) the two first tracks have the **same** `gmem_index`.

I kept testing, saving the project in different configurations (no track selected, one track selected), closing and reopen it, and it worked correctly every time until I saved with **all tracks  selected**. On reopening, the 1st and last tracks had the **same** `gmem_index`.  But after closing and reopening the project, everything was correct. I tried to repeat the sequence (select all tracks, save, close and reopen) but this time it caused no error, so still some random behavior...

**Comment by jtackaberry** [comment] 2020-05-25 13:27
Hm, the `uuid=0` in the lock manager section in the JSFX debug output is definitely unexpected.

Could I trouble you to set `Log Level` to `Debug` in Reaticulate's settings page, try to reproduce this again, and then paste the console output here?

**Comment by rgruet** [comment] 2020-05-25 17:14
This time the problem occurred after I deleted my 3rd track, saved and reopened the project. Here is the **ReaScript console output**:
```
19:03:49.635 [INFO]  baseapp: Reaticulate log level is DEBUG
19:03:49.635 [DEBUG]  baseapp: theme bg is #333333
19:03:49.644 [INFO]  reabank: init files factory=/Users/rgruet/Desktop/Reaper portable/Scripts/Reaticulate/Reaticulate-factory.reabank user=/Users/rgruet/Desktop/Reaper portable/Data/Reaticulate.reabank

19:03:49.644 [DEBUG]  (0 / 0 ms)  reabank: tmp file exists: /Users/rgruet/Desktop/Reaper portable/Data/Reaticulate-tmp2.reabank
19:03:49.692 [INFO]  (48 / 48 ms)  reabank: existing materialized reabank parsed

19:03:49.696 [INFO]  baseapp: showing screen banklist
19:03:49.696 [INFO]  rfx: assigning 2131452246.0 as lock manager
19:03:49.696 [INFO]  baseapp: showing screen installer
19:03:49.710 [INFO]  baseapp: js_ReaScriptAPI extension is available
19:04:04.233 [DEBUG]  rfx: read version=1.0 from offset=3000.0
19:04:04.233 [DEBUG]  rfx: deserialize ver=1.0 from 3000.0 took: 8.9000000000006e-05
19:04:04.234 [DEBUG]  rfx: bank=SCS - V1 Core  hash: 818923497 vs. 818923497
19:04:04.234 [INFO]  baseapp: showing screen banklist
19:04:05.399 [DEBUG]  rfx: read version=1.0 from offset=3000.0
19:04:05.399 [DEBUG]  rfx: deserialize ver=1.0 from 3000.0 took: 9.0000000000146e-05
19:04:05.399 [DEBUG]  rfx: bank=SCS - V1 Core  hash: 818923497 vs. 818923497
19:05:01.837 [INFO]  rfx: lock manager heartbeat timeout (1495.6220703125ms)
19:05:01.837 [INFO]  rfx: assigning 2131448378.0 as lock manager
19:05:01.847 [INFO]  rfx: lock manager heartbeat timeout (1522.2001953125ms)
19:05:01.847 [INFO]  rfx: no eligible instance to serve as lock manager
19:08:17.556 [INFO]  rfx: assigning 2131452246.0 as lock manager
19:08:35.505 [INFO]  rfx: lock manager heartbeat timeout (518.61499023438ms)
19:08:35.505 [INFO]  rfx: assigning 2131448378.0 as lock manager
19:08:35.511 [INFO]  rfx: lock manager heartbeat timeout (552.10595703125ms)
19:08:35.511 [INFO]  rfx: no eligible instance to serve as lock manager
19:11:44.193 [INFO]  rfx: assigning 2131448378.0 as lock manager
19:11:50.177 [INFO]  rfx: lock manager heartbeat timeout (519.76000976562ms)
19:11:50.177 [INFO]  rfx: assigning 2131452246.0 as lock manager
19:11:50.185 [INFO]  rfx: lock manager heartbeat timeout (553.9580078125ms)
19:11:50.185 [INFO]  rfx: no eligible instance to serve as lock manager
19:11:54.683 [INFO]  rfx: assigning 2131452246.0 as lock manager
19:11:59.447 [INFO]  rfx: lock manager heartbeat timeout (510.31005859375ms)
19:11:59.447 [INFO]  rfx: assigning 2131448378.0 as lock manager
19:11:59.454 [INFO]  rfx: lock manager heartbeat timeout (544.71215820312ms)
19:11:59.454 [INFO]  rfx: no eligible instance to serve as lock manager
19:12:11.873 [INFO]  rfx: assigning 2131452246.0 as lock manager
19:12:11.880 [INFO]  rfx: lock manager heartbeat timeout (12873.205078125ms)
19:12:11.880 [INFO]  rfx: no eligible instance to serve as lock manager
19:12:11.901 [INFO]  rfx: assigning 2131452246.0 as lock manager

```
... and here is the **Reaper window**:

![Screenshot 2020-05-25 at 19 09 21](https://user-images.githubusercontent.com/6683823/82832412-4613d800-9ebb-11ea-9111-6de69c42632e.png)

**Comment by jtackaberry** [comment] 2020-05-25 17:22
Yikes, this is a mess. :(

Ok, I'm going to make an educated guess here that you have the `Audio | Playback | Run FX when stopped` Reaper preference disabled?

**Comment by jtackaberry** [comment] 2020-05-25 17:41
"Run FX when stopped" being disabled could definitely explain some of the original weirdness (before this attempted fix/workaround).  But OTOH I see this option is *enabled* in a fresh portable Reaper install, and you saw it with a portable install as well, so perhaps not.

But if you tested the fix in your main install with this option disabled, it could at least explain all those "heartbeat timeout" log lines.

**Comment by rgruet** [comment] 2020-05-25 17:57
In both my usual and my fresh portable Reaper installs the "Run FX when stopped" option is (and has always been) **enabled**. 

My last test with all the heartbeat timeouts was run on my portable install of Reaper, and the option was enabled.

**Comment by rgruet** [comment] 2020-05-25 18:08
In another instance of the error occurring just after opening the project (on my portable install), without any other action on my part, the debug **doesn't show timeouts**:

```
20:01:47.668 [INFO]  baseapp: Reaticulate log level is DEBUG
20:01:47.668 [DEBUG]  baseapp: theme bg is #333333
20:01:47.676 [INFO]  reabank: init files factory=/Users/rgruet/Desktop/Reaper portable/Scripts/Reaticulate/Reaticulate-factory.reabank user=/Users/rgruet/Desktop/Reaper portable/Data/Reaticulate.reabank

20:01:47.677 [DEBUG]  (0 / 0 ms)  reabank: tmp file exists: /Users/rgruet/Desktop/Reaper portable/Data/Reaticulate-tmp2.reabank
20:01:47.721 [INFO]  (44 / 44 ms)  reabank: existing materialized reabank parsed

20:01:47.724 [INFO]  baseapp: showing screen banklist
20:01:47.724 [INFO]  rfx: assigning 331695702.0 as lock manager
20:01:47.724 [INFO]  rfx: instance missing gmem_index: 331692346.0 (locked by 0.0)
20:01:47.724 [INFO]  baseapp: showing screen installer
20:01:47.738 [INFO]  baseapp: js_ReaScriptAPI extension is available
20:01:47.738 [DEBUG]  rfx: read version=1.0 from offset=3000.0
20:01:47.738 [DEBUG]  rfx: deserialize ver=1.0 from 3000.0 took: 7.299999999999e-05
20:01:47.738 [DEBUG]  rfx: bank=SCS - V1 Core  hash: 818923497 vs. 818923497
20:01:47.739 [INFO]  baseapp: showing screen banklist 
```
... yet the `gmem_index` of both tracks are the same:

![Screenshot 2020-05-25 at 20 07 05](https://user-images.githubusercontent.com/6683823/82835124-66479500-9ec3-11ea-8898-7fc917efe37b.png)

**Comment by jtackaberry** [comment] 2020-05-25 18:30
I see a problem with the heartbeat timeout detection code, but actually the bigger problem I have is the line "no eligible instance to serve as lock manager" which tells me that the JSFX instances aren't having their `@block` evaluated nearly as fast as I expect they should (and as fast as on my system).

That aside, your latest update shows clearly there is some raciness not fundamentally solved by these changes.   Will chew on this for a bit longer.

Thanks for your testing and patience. :)

**Comment by jtackaberry** [comment] 2020-05-25 18:49
Ah, it just occurred to me that the "no eligible instance" thing could be explained by the audio interface being disabled when Reaper loses focus, which would suspend FX processing.   Do you recall switching windows during your earlier test that could account for that?

**Comment by rgruet** [comment] 2020-05-25 20:48
I don't remember what I did on my earlier test, but I tried again and yes every time I select a window outside Reaper (making it lose focus) the "`rfx: no eligible instance to serve as lock manager`" debug message shows up.

**Comment by jtackaberry** [comment] 2020-05-25 21:33
Ok, that makes me feel a bit better about their presence.  That should be innocuous then.

I spotted another little bit of raciness that could explain the collision you saw.  I can reproduce it on my system but it's *so* rare (20-30 full restarts of Reaper to trigger it).  Take this one out for a spin.

[Reaticulate-gmem_index_race_fix-20200525.zip](https://github.com/jtackaberry/reaticulate/files/4678901/Reaticulate-gmem_index_race_fix-20200525.zip)

**Comment by rgruet** [comment] 2020-05-25 22:34
Good news! With your new fix I was unable to reproduce the error with 2, 3 and even 4 tracks and many trials, in all cases the `gmem_index` value was different for each track and (consequently) the correct patch was displayed for the selected track.

**Comment by jtackaberry** [comment] 2020-05-26 00:31
Thanks Richard.  I've reproduced a slimmed down test case demonstrating the fact that `atomic_setifequal()` doesn't work with global variables and asked again on the Reaper forum.

It'd be nice to get a proper fix in JSFX to provide some mechanism to synchronize across instances, but I'm not very optimistic it'll get noticed by the developers.  (Although I've found what catches their attention is dictated by alignment of stars, phase of the moon, quantum spin of particles, etc.)  Assuming that doesn't go anywhere, at least we seem to have a fix, even if it is a little gross.

Please report back if you run into any more issues, otherwise I think I'll push out a prerelease with these changes in a couple days.

Thanks for everything!

**Comment by rgruet** [comment] 2020-05-26 11:20
I'll continue testing your fix on my standard Reaper install and keep you posted.

Thank you for having created Reaticulate, it's such an invaluable tool for musicians, compared to these barbaric and user unfriendly ways of directly inserting CCs or notes to switch articulations, it really should be standard on all DAWs!

**Comment by rgruet** [comment] 2020-05-26 11:42
I couldn't find the `atomic_xxx()` functions documentation any longer in the [EEL2 documentation](https://www.cockos.com/EEL2/index.php), they seem to have disappeared! Maybe Reaper developers have heard you and removed them while they are either fixing them or even designing new, better synchronization mechanisms, let's be outrageously optimistic ;-)

**Comment by jtackaberry** [comment] 2020-05-26 11:49
Hm, I actually never saw that particular page before. I'd been using http://reaper.fm/sdk/js/advfunc.php#js_advanced as the reference and the atomic functions are still there. Are you saying you saw those functions at the page you linked to before?

I find I'm not really sure what the difference between those two docs are, except the latter seems more complete. Maybe one is a general EEL2 reference (for ReaScript) and the latter is specific to JSFX, which as some additional idiosyncrasies.

**Comment by rgruet** [comment] 2020-05-26 12:58
Now that you mention it, I do remember having seen them in the "advanced" page. I couldn't find them in the other doc, and probably a surge of optimism led me to conveniently forget about the existence of this page and build this fantasy of Reaper developers interested in fixing the concurrency handling limitations... 

I love Reaper, but I think the API documentation is not at par with the general quality of the software (at least by my standards). IMO an API without a good documentation, unless trivial, is quite like having no API at all. But I'm digressing, that's (somehow) beyond the scope of this bug report ;-)

**Comment by jtackaberry** [comment] 2020-05-26 13:54
It's best not to get me started about the ReaScript API. :)  Its lack of design intent is one of my long standing annoyances, instead feeling like the product of evolution paired with a dysfunctional selection process.  Getters without setters, [setters without getters](https://forums.cockos.com/showthread.php?t=204173), incomplete APIs that would become [massively more useful with trivial changes](https://vi-control.net/community/threads/what-is-reaper-bad-at.62334/#post-4093109), I could go on (and have).

(Alas, I guess I got myself started after all.)

**Comment by rgruet** [comment] 2020-05-27 00:05
Not everyone is impacted by a poorly designed and/or documented API, only people willing to customize or extend Reaper at the code level.  But this reflects the way Reaper's developers think and act. And I'm convinced this mindset -  regardless of their sheer coding skills - eventually makes their lives more difficult in term of ease of maintenance and evolution.

That's funny you mention Corba (that I [practiced a long time ago](http://rgruet.free.fr/ipy/)) as a good example of design-by-committee (which it is, among many others).
I was just trying to remember the name of the anti-pattern describing the _opposite_ approach probably followed by Reaper's developers: It is when **you start building a garden shed and then you make it evolve into a building**, which is not without consequences on the consistency of design, implementation and documentation ;-) 

Anyway, I don't know of any other DAW which offers such a level of customization (by far), and that's probably a significant part of my attraction for Reaper. So like you I'll still take it as it is, but with some regrets (sniff). 

(Darn, I am digressing again...)

**Comment by jtackaberry** [comment] 2020-05-27 00:17
I mentioned CORBA because, if you recall, we reminisced about it in an email exchange last year. I had done Python bindings in a project called ORBit-Python just a hair over 20 years ago now.  Damn, so old. 👴

It's such a great example of committee-designed bloat, and seeing where the industry has landed is a telling cautionary tale.

Reaper's extensibility is also what keeps me using it.  But I figure by now I've earned my stripes enough to be able to shit on it too. :)

**Comment by rgruet** [comment] 2020-05-27 00:53
Alas Jason, I had no recollection of having exchanged with you about Corba last year, that's the tragedy of aging I'm afraid ;-)

**Comment by rgruet** [comment] 2020-06-03 20:31
A brief update to let you know that since your last fix I haven't experienced any problem :-)

**Comment by jtackaberry** [comment] 2020-06-03 22:30
Awesome, great to know, thanks Richard.  That's a very solid plan B.

Current plan A is now to wait and see what Justin comes up with.  He acknowledged the issue on the [thread I started](https://forum.cockos.com/showthread.php?p=2293072).  It's been a few days, so I'll probably bump it over the weekend.

**Comment by jtackaberry** [comment] 2020-06-04 13:39
Good news: the [latest Reaper prerelease](https://forum.cockos.com/showthread.php?t=237610) now has a fix to allow `atomic_*()` to work across JSFX instances.  I'm quite relieved to know that our ugly hack won't be necessary. :)

**Comment by jtackaberry** [comment] 2020-06-04 13:41
@rgruet if you're inclined, it would be great if you could take the prerelease out for a spin in a portable install with an unmodified stock install of Reaticulate 0.4.5.  You've much more luck (or unluck) of reproducing the issue than me.

**Comment by rgruet** [comment] 2020-06-04 18:26
Is this the correct version to try: [reaper611+dev0603_x86_64.dmg](https://www.landoleet.org/reaper611+dev0603_x86_64.dmg) ?

**Comment by jtackaberry** [comment] 2020-06-04 18:54
> Is this the correct version to try: reaper611+dev0603_x86_64.dmg ?

Yep.

**Comment by rgruet** [comment] 2020-06-04 20:15
Looks like it works :-)  I could not reproduce the problem with this pre-release version of Reaper and the standard Reaticulate 0.4.5.
So you managed to convince Justin to fix the concurrency issue in Reaper (quite an achievement)! **Plus** you can now get rid of this awful (albeit functional) workaround ;-) Isn't life wonderful (sometimes)?

**Comment by jtackaberry** [comment] 2020-06-04 20:40
Yes, I'm quite happy about this outcome. :)

When this lands in an official Reaper release I'll close this issue.

**Comment by jtackaberry** [comment] 2020-06-15 14:45
Reaper 6.12 was just released with the fix, so I'm closing this issue.  Thanks for all your help, Richard.

**Closed by jtackaberry** 2020-06-15 14:45 UTC
Labels: bug, reaper limitation
