### ISSUE TITLE
Reaper crashes with Reaticulate

### ISSUE THREAD

**Issue by SebastienLi** [jtackaberry/reaticulate#159] opened 2022-01-27 19:58 UTC
Hi,

I've got an issue with Reaticulate. After inserting some articulations (CC) and closing the piano roll if I use the space bar to play the track, Reaper crashes... 

I did the latest update of Reaticulate but no changes.

Thanks in advance!

**Comment by jtackaberry** [comment] 2022-01-27 20:06
Hi @SebastienLi 

REAPER crashes would definitely be a REAPER bug.  Are there any early warning signs of instability, like any error messages popping up or other weirdness? Or is it basically just press spacebar and bang, byebye REAPER?

If I can reproduce the problem though I might be able to facilitate the bug report to the REAPER developers.  A few questions:

1. Is this reliably repeatable for you, or intermittent?
2. What is your OS and system specs?
3. Can you provide a sample RPP project file and accompanying .Reabank file that reproduces it?

Thanks!

**Comment by SebastienLi** [comment] 2022-01-28 08:44
Hi,

Thanks for your response.

I will try to describe the best I can do.

1. Is this reliably repeatable for you, or intermittent?
Yes, I can reproduce the issue all the time.  When I change articulations and I close the piano roll and then use the space bar to play the track Reaper crashes.  I need save my work each time I change articulations.

2. What REAPER version?
The latest version : v6.46

3. What is your OS and system specs?
Mac OS 10.15.7
Intel 3.2GHz i5
16Go DDR3

4.Can you provide a sample RPP project file and accompanying .Reabank file that reproduces it?
I put in attachment a simple RPP project file in which I have the issue and my Reabank file. I put also a file I don't know what it is (Reaticulate-tmp183.reabank)

Thanks a lot!

Sébastien


[Test_files.zip](https://github.com/jtackaberry/reaticulate/files/7957089/Test_files.zip)

**Comment by jtackaberry** [comment] 2022-01-28 17:37
Thanks for sharing this Sébastien. Unfortunately (or fortunately?) I'm not able to reproduce the crash here.  Tried in both Windows and OSX (admittedly an older version: 10.14.4).  I set the Reaticulate.reabank file you shared, loaded the project, opened the MIDI item in the MIDI editor, added an articulation, closed the editor, start playback via spacebar, and all is well.

A couple more questions to help further the troubleshooting:
1. If you remove the patch from Kontakt and just have an empty Kontakt instance, does it still crash?
2. What about if you remove Kontakt from the track altogether, and just have Reaticulate by itself on there?
3. Can you reproduce it on a fresh portable REAPER install with stock settings?

Thanks!

**Comment by SebastienLi** [comment] 2022-01-28 18:03
Hi,

Thanks for your return!

I just tried without the patch from Kontakt and without Kontakt, just the track with Reaticulate. Both cause crash:(

However, most of the time, Reaper crashes not the first time.  I need to change or to add some articulations to get the issue. 

It's difficult for me right now to try a fresh portable Reaper.  I'm sorry.

Sébastien

**Comment by SebastienLi** [comment] 2022-01-29 09:15
Hi,

I was not able to reproduce the crash on a fresh portable Reaper install. So the problem is my settings, I suppose.  

Is it a way to find the problem without doing a new install of Reaper?

Thanks in advance for your advice!

Sébastien

**Comment by SebastienLi** [comment] 2022-01-29 10:46
Hi,

I delete the js_ReaScriptAPI extension (v0.990) and replace it by v.1.217 and it seems working.  I don't want to be happy too soon but after several tries I do not have the issue:)

I will keep you informed in the next few days.

Thanks for all!

Sébastien

**Comment by jtackaberry** [comment] 2022-01-29 15:06
Great sleuthing, Sébastien. I'm happy to hear things are working so far.  I'll close this issue now but if you do run into further issues please follow up and we'll reopen the investigation.

**Closed by jtackaberry** 2022-01-29 15:06 UTC
