### ISSUE TITLE
Per Articulation Delay Offset Feature Request!! 

### ISSUE THREAD

**Issue by 813rico** [jtackaberry/reaticulate#223] opened 2023-11-17 00:58 UTC
I would like to start by thanking you for this tool.

With that being said, is there any way you could add per articulation delays? Some libraries' articulations have different delay offsets and makes me basically ditch keyswitching all around since i like to stay in the grid and not nudge the notes.

I saw Dorico implemented this in their last update and if you can somehow work with Cockos that would be amazing. Us film composers on REAPER exist!

Thank you again.

Juan

**Comment by jtackaberry** [comment] 2023-11-25 16:01
Would like to implement this.  REAPER has the plumbing for it, it's just a) trickier than you might expect to get right in practice and b) requires significant changes to Reaticulate to support it.

This is is a duplicate of #130 -- see that issue for more discussion.

**Closed by jtackaberry** 2023-11-25 16:01 UTC
